export const CAMISETAS = [
  {
    img: 'zonadribling/static/assets/camisetas/monaco.png',
    alt: 'Camiseta Mónaco',
    texto: 'Camiseta Mónaco',
    team: 'Mónaco',
    league: 'Francia League 1',
    nationalTeam: 'Francia',
    retro: false,
  },
  {
    img: 'zonadribling/static/assets/camisetas/atletico-madrid.png',
    alt: 'Atlético Madrid',
    texto: 'Camiseta Atlético Madrid',
    team: 'Atlético Madrid',
    league: 'LaLiga',
    nationalTeam: 'España',
    retro: false,
  },
  {
    img: 'zonadribling/static/assets/camisetas/fc-barcelona.png',
    alt: 'FC Barcelona',
    texto: 'Camiseta FC Barcelona',
    team: 'FC Barcelona',
    league: 'LaLiga',
    nationalTeam: 'España',
    retro: false,
  },
  {
    img: 'zonadribling/static/assets/camisetas/psg.png',
    alt: 'PSG',
    texto: 'Camiseta PSG',
    team: 'PSG',
    league: 'Francia League 1',
    nationalTeam: 'Francia',
    retro: false,
  },
  {
    img: 'zonadribling/static/assets/camisetas/atalanta.png',
    alt: 'Atalanta',
    texto: 'Camiseta Atalanta',
    team: 'Atalanta',
    league: 'Serie A',
    nationalTeam: 'Italia',
    retro: false,
  },
];
